IssueComment
  { issueCommentUpdatedAt = 2015 (-08) (-13) 04 : 50 : 09 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 505365
        , simpleUserLogin = N "danielmewes"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/505365?v=3"
        , simpleUserUrl = "https://api.github.com/users/danielmewes"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/130535039"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/4685#issuecomment-130535039"
  , issueCommentCreatedAt = 2015 (-08) (-13) 04 : 50 : 09 UTC
  , issueCommentBody =
      "That being said I think there's another bug close to this that could cause a seg fault (maybe even #4675?). Looking into that now."
  , issueCommentId = 130535039
  }