IssueComment
  { issueCommentUpdatedAt = 2015 (-02) (-26) 22 : 09 : 29 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 505365
        , simpleUserLogin = N "danielmewes"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/505365?v=3"
        , simpleUserUrl = "https://api.github.com/users/danielmewes"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/76285241"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/3837#issuecomment-76285241"
  , issueCommentCreatedAt = 2015 (-02) (-26) 22 : 09 : 29 UTC
  , issueCommentBody =
      "@alimoeeny Thanks. It turns out #3791 was also inside a boot2docker container, so I assume it's the same issue. We'll try to work around it in the next release.\r\n\r\nAt the moment I fear RethinkDB doesn't run inside a boot2docker container, at least not with the default configuration. I don't know much about how boot2docker works. It might be possible to make it not use a VirtualBox shared folder for the data, but I'm not sure."
  , issueCommentId = 76285241
  }