IssueComment
  { issueCommentUpdatedAt = 2015 (-06) (-24) 20 : 16 : 35 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 505365
        , simpleUserLogin = N "danielmewes"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/505365?v=3"
        , simpleUserUrl = "https://api.github.com/users/danielmewes"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/114997722"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/4447#issuecomment-114997722"
  , issueCommentCreatedAt = 2015 (-06) (-24) 20 : 16 : 35 UTC
  , issueCommentBody =
      "Thanks for opening an issue about this @graycatfromspace .\r\n\r\nWe will see if we can reproduce this, though I still think that it might be an issue with the configuration and not with RethinkDB. Maybe something about how Debian sets the user limits?"
  , issueCommentId = 114997722
  }