Issue
  { issueClosedAt = Just 2013 (-06) (-25) 01 : 02 : 59 UTC
  , issueUpdatedAt = 2013 (-06) (-25) 01 : 17 : 57 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/1073/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/rethinkdb/issues/1073"
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 1073
  , issueAssignee = Nothing
  , issueUser =
      SimpleUser
        { simpleUserId = Id 517280
        , simpleUserLogin = N "cwsterling"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/517280?v=3"
        , simpleUserUrl = "https://api.github.com/users/cwsterling"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "Killed database trying to create a secondary index on 42000+ records"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/1073"
  , issueCreatedAt = 2013 (-06) (-25) 00 : 27 : 23 UTC
  , issueBody =
      Just
        "I'm running Ubuntu 12.10\nWhen starting Rethinkdb, the following information is printed to the console:\n\n```\ninfo: Running rethinkdb 1.6.1-0ubuntu1~quantal (GCC 4.7.2)...\ninfo: Running on Linux 3.5.0-17-generic x86_64\n```\n\nIn the log_file, this is after I tried to reboot the server, I see this\n\n```\n2013-06-24T19:57:32.669877604 53.874824s error: Error in src/buffer_cache/mirrored/mirrored.cc at line 984:\n2013-06-24T19:57:32.670260150 53.875207s error: Guarantee failed: [!token_pair->sindex_write_token.has()] \n2013-06-24T19:57:32.670785190 53.875732s error: Backtrace:\n2013-06-24T19:57:32.671549239 53.876496s error: Mon Jun 24 19:57:32 2013\\n\\n1: rethinkdb() [0x560c91]\\n2: rethinkdb() [0x5f1b9e]\\n3: rethinkdb() [0x5c05d6]\\n4: rethinkdb() [0x5c0659]\\n5: rethinkdb() [0x505163]\\n6: rethinkdb() [0x43ecd1]\\n7: rethinkdb() [0x441cce]\\n8: rethinkdb() [0x44033e]\\n9: rethinkdb() [0x5e695e]\n2013-06-24T19:57:32.673324446 53.878271s error: Exiting.\n```\n\nWhen I viewed the console right after it crashed, it just said \"Killed\" or something. I don't remember and my console history doesn't go that far back because i'm using screen and it cut off further up\n\nI tried to restart the server, it started, but said that I had 1 issue and that 0/1 shards were reachable. I stopped it, and it spent a while writing data and that is when I got the error above. After starting it again and letting it sit for a while, it managed to come back up with the generated secondary index.\n"
  , issueState = "closed"
  , issueId = Id 15955626
  , issueComments = 4
  , issueMilestone =
      Just
        Milestone
          { milestoneCreator =
              SimpleUser
                { simpleUserId = Id 706854
                , simpleUserLogin = N "AtnNn"
                , simpleUserAvatarUrl =
                    "https://avatars.githubusercontent.com/u/706854?v=3"
                , simpleUserUrl = "https://api.github.com/users/AtnNn"
                , simpleUserType = OwnerUser
                }
          , milestoneDueOn = Nothing
          , milestoneOpenIssues = 1
          , milestoneNumber = 17
          , milestoneClosedIssues = 595
          , milestoneDescription =
              Just
                "The scope of this issue is covered by another issue. The closing comment should link to the other issue."
          , milestoneTitle = "duplicate"
          , milestoneUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/milestones/17"
          , milestoneCreatedAt = 2013 (-03) (-29) 20 : 23 : 12 UTC
          , milestoneState = "closed"
          }
  }