Issue
  { issueClosedAt = Just 2015 (-03) (-24) 02 : 32 : 08 UTC
  , issueUpdatedAt = 2015 (-03) (-24) 02 : 32 : 11 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/1761/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/rethinkdb/issues/1761"
  , issueClosedBy = Nothing
  , issueLabels =
      [ IssueLabel
          { labelColor = "e10c02"
          , labelUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/labels/pr:high"
          , labelName = "pr:high"
          }
      ]
  , issueNumber = 1761
  , issueAssignee = Nothing
  , issueUser =
      SimpleUser
        { simpleUserId = Id 292681
        , simpleUserLogin = N "nergdron"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/292681?v=3"
        , simpleUserUrl = "https://api.github.com/users/nergdron"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "Large delete fails, causes further operations to fail."
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/1761"
  , issueCreatedAt = 2013 (-12) (-12) 19 : 12 : 33 UTC
  , issueBody =
      Just
        "Per conversation on IRC with @atnnn:\r\n\r\nI've just set up a 3 node cluster with the latest release on CentOS 6 (rethinkdb-1.11.2-1.11.2.x86_64). I pushed about 6.5M records into test.test doing some insert benchmarking, and though I'd test delete performance by timing the following:\r\n\r\nr.db('test').table('test').delete()\r\n\r\nI left it running last night, and when I came it, the query was still just sitting in the web UI, never completed. Now, other queries through the web UI are failing that should complete almost instantly, such as the following:\r\n\r\nr.db('test').table('test').limit(10)\r\n\r\nNote that all 3 systems are responsive, and the web UI still loads new pages and graph data, so the server processes don't appear to be completely dead. I'm sure if I restart the daemons, that'll clear this issue, but I thought since it's a test cluster it'd be worth investigating the problem further before I do so.\r\n\r\nLet me know what I can do or run to get you guys further information on this problem. Log file under /var/lib/rethinkdb/default/data/log_file on each node doesn't appear to have any useful information in it.\r\n"
  , issueState = "closed"
  , issueId = Id 24201044
  , issueComments = 17
  , issueMilestone =
      Just
        Milestone
          { milestoneCreator =
              SimpleUser
                { simpleUserId = Id 706854
                , simpleUserLogin = N "AtnNn"
                , simpleUserAvatarUrl =
                    "https://avatars.githubusercontent.com/u/706854?v=3"
                , simpleUserUrl = "https://api.github.com/users/AtnNn"
                , simpleUserType = OwnerUser
                }
          , milestoneDueOn = Nothing
          , milestoneOpenIssues = 0
          , milestoneNumber = 64
          , milestoneClosedIssues = 228
          , milestoneDescription =
              Just
                "These issues are no longer relevant to the current version of RethinkDB"
          , milestoneTitle = "outdated"
          , milestoneUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/milestones/64"
          , milestoneCreatedAt = 2014 (-03) (-28) 00 : 17 : 40 UTC
          , milestoneState = "closed"
          }
  }