Issue
  { issueClosedAt = Just 2013 (-04) (-08) 21 : 43 : 24 UTC
  , issueUpdatedAt = 2013 (-04) (-10) 21 : 08 : 45 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/568/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/rethinkdb/issues/568"
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 568
  , issueAssignee =
      Just
        SimpleUser
          { simpleUserId = Id 1777134
          , simpleUserLogin = N "mlucy"
          , simpleUserAvatarUrl =
              "https://avatars.githubusercontent.com/u/1777134?v=3"
          , simpleUserUrl = "https://api.github.com/users/mlucy"
          , simpleUserType = OwnerUser
          }
  , issueUser =
      SimpleUser
        { simpleUserId = Id 91093
        , simpleUserLogin = N "mfenniak"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/91093?v=3"
        , simpleUserUrl = "https://api.github.com/users/mfenniak"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "Uncaught exception from concatMap if func does not return sequence"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/568"
  , issueCreatedAt = 2013 (-04) (-01) 23 : 31 : 54 UTC
  , issueBody =
      Just
        "I've come across a crash that occurs in RethinkDB 1.4.2 (Linux/x86-64) when using concatMap if my map function returns a non-SEQUENCE data type.  Here are the steps to reproduce:\n1. `r.dbCreate(\"test\")`\n2. `r.db(\"test\").tableCreate(\"table\")`\n3. `r.db(\"test\").table(\"table\").insert({\"name\":\"Jim Brown\"})`\n4. `r.db(\"test\").table(\"table\").concatMap(function(rec) { return rec(\"name\"); })`; here's the bad query.  As I understand it, concatMap requires a sequence return value, where I've provided string field.\n5. Observe crash:\n\n```\ninfo: Running rethinkdb 1.4.2-1ubuntu1~quantal (GCC 4.7.2)...\ninfo: Running on Linux 3.7.0-7-generic x86_64\ninfo: Loading data from directory rethinkdb_data\ninfo: Listening for intracluster connections on port 29015\ninfo: Listening for client driver connections on port 28015\ninfo: Listening for administrative HTTP connections on port 8080\ninfo: Listening on addresses: 127.0.0.1, 127.0.1.1\ninfo: To fully expose RethinkDB on the network, bind to all addresses\ninfo: by running rethinkdb with the `--bind all' command line option.\ninfo: Server ready\nVersion: rethinkdb 1.4.2-1ubuntu1~quantal (GCC 4.7.2)\nerror: Error in src/errors.cc at line 111:\nerror: Uncaught exception of type \"ql::datum_exc_t\"\n         what(): Cannot convert STRING to SEQUENCE\nerror: Backtrace:\nerror: Mon Apr  1 17:23:29 2013\n\n       1: rethinkdb() [0x83b751]\n... snip pointless backtrace w/ no symbols ...\n       25: rethinkdb() [0x8653fe]\nerror: Exiting.\nTrace/breakpoint trap (core dumped)\n```\n\nExpected behavior: an error message response.\n"
  , issueState = "closed"
  , issueId = Id 12682093
  , issueComments = 11
  , issueMilestone =
      Just
        Milestone
          { milestoneCreator =
              SimpleUser
                { simpleUserId = Id 706854
                , simpleUserLogin = N "AtnNn"
                , simpleUserAvatarUrl =
                    "https://avatars.githubusercontent.com/u/706854?v=3"
                , simpleUserUrl = "https://api.github.com/users/AtnNn"
                , simpleUserType = OwnerUser
                }
          , milestoneDueOn = Nothing
          , milestoneOpenIssues = 0
          , milestoneNumber = 22
          , milestoneClosedIssues = 5
          , milestoneDescription = Nothing
          , milestoneTitle = "1.4.3"
          , milestoneUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/milestones/22"
          , milestoneCreatedAt = 2013 (-04) (-01) 21 : 43 : 59 UTC
          , milestoneState = "closed"
          }
  }