Issue
  { issueClosedAt = Just 2016 (-07) (-07) 23 : 56 : 14 UTC
  , issueUpdatedAt = 2016 (-08) (-30) 01 : 49 : 12 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/5904/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/rethinkdb/issues/5904"
  , issueClosedBy = Nothing
  , issueLabels =
      [ IssueLabel
          { labelColor = "e102d8"
          , labelUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/labels/tp:bug"
          , labelName = "tp:bug"
          }
      ]
  , issueNumber = 5904
  , issueAssignee =
      Just
        SimpleUser
          { simpleUserId = Id 505365
          , simpleUserLogin = N "danielmewes"
          , simpleUserAvatarUrl =
              "https://avatars.githubusercontent.com/u/505365?v=3"
          , simpleUserUrl = "https://api.github.com/users/danielmewes"
          , simpleUserType = OwnerUser
          }
  , issueUser =
      SimpleUser
        { simpleUserId = Id 7917
        , simpleUserLogin = N "bsharpe"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/7917?v=3"
        , simpleUserUrl = "https://api.github.com/users/bsharpe"
        , simpleUserType = OwnerUser
        }
  , issueTitle = "Crash Proxy using Ruby"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/5904"
  , issueCreatedAt = 2016 (-07) (-01) 17 : 12 : 50 UTC
  , issueBody =
      Just
        "Working on a small reproducible case for this, but the general gist is:\r\n\r\n- connect to a proxy that's connected to a cluster \r\n- using the ruby driver, create a cursor on a table with a large number of row (not sure that's relevant)\r\n- save this data to a different connection to a different node (copying data from remote to local)\r\n- Ctrl-C cancel the import process\r\n- remote Proxy dies every time\r\n- tend to think it's the Ruby driver not getting a chance to close the connection properly\r\n\r\n```\r\n2016-06-27T14:39:05.864845985 317.677548s error: Error in src/errors.cc at line 161:\r\n2016-06-27T14:39:05.864871941 317.677574s error: Uncaught exception of type \"tcp_conn_read_closed_exc_t\"\\n  what(): Network connection read end closed\r\n2016-06-27T14:39:05.864879717 317.677582s error: Backtrace:\r\n2016-06-27T14:39:05.974798536 317.787517s error: Mon Jun 27 14:39:05 2016\\n\\n1 [0xabb110]: backtrace_t::backtrace_t() at ??:?\\n2 [0xabb4a3]: format_backtrace(bool) at ??:?\\n3 [0xd3\r\n2016-06-27T14:39:05.974866901 317.787569s error: Exiting.\r\n```\r\n"
  , issueState = "closed"
  , issueId = Id 163437918
  , issueComments = 5
  , issueMilestone =
      Just
        Milestone
          { milestoneCreator =
              SimpleUser
                { simpleUserId = Id 505365
                , simpleUserLogin = N "danielmewes"
                , simpleUserAvatarUrl =
                    "https://avatars.githubusercontent.com/u/505365?v=3"
                , simpleUserUrl = "https://api.github.com/users/danielmewes"
                , simpleUserType = OwnerUser
                }
          , milestoneDueOn = Just 2016 (-08) (-04) 07 : 00 : 00 UTC
          , milestoneOpenIssues = 0
          , milestoneNumber = 126
          , milestoneClosedIssues = 39
          , milestoneDescription = Just ""
          , milestoneTitle = "2.3.5"
          , milestoneUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/milestones/126"
          , milestoneCreatedAt = 2016 (-07) (-28) 21 : 38 : 16 UTC
          , milestoneState = "closed"
          }
  }