Issue
  { issueClosedAt = Just 2016 (-08) (-29) 20 : 23 : 40 UTC
  , issueUpdatedAt = 2016 (-08) (-29) 20 : 23 : 40 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/6082/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/rethinkdb/issues/6082"
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 6082
  , issueAssignee = Nothing
  , issueUser =
      SimpleUser
        { simpleUserId = Id 7919852
        , simpleUserLogin = N "modirajdeep"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/7919852?v=3"
        , simpleUserUrl = "https://api.github.com/users/modirajdeep"
        , simpleUserType = OwnerUser
        }
  , issueTitle = "App crashes when disconnected from internet."
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/6082"
  , issueCreatedAt = 2016 (-08) (-29) 13 : 19 : 09 UTC
  , issueBody =
      Just
        "I'm on rethinkdb 2.3.3 on windows. When my laptop disconnects from the internet, my node.js app crashes with this error -\n\n```\nevents.js:160\n      throw er; // Unhandled 'error' event\n      ^\n\nError: getaddrinfo ENOENT localhost:80\n    at Object.exports._errnoException (util.js:1012:11)\n    at errnoException (dns.js:33:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)\n```\n\nWhen I try restarting the app I get this error -4\n\n```\n{ ReqlDriverError: Could not connect to localhost:28015.\ngetaddrinfo ENOENT localhost:28015\n    at ReqlDriverError.ReqlError [as constructor] (D:\\Axelta IOT\\test\\node_modules\\rethinkdb\\errors.js:23:13)\n    at new ReqlDriverError (D:\\Axelta IOT\\test\\node_modules\\rethinkdb\\errors.js:68:50)\n    at TcpConnection.<anonymous> (D:\\Axelta IOT\\test\\node_modules\\rethinkdb\\net.js:94:27)\n    at TcpConnection.g (events.js:286:16)\n    at emitOne (events.js:96:13)\n    at TcpConnection.emit (events.js:188:7)\n    at Socket.<anonymous> (D:\\Axelta IOT\\test\\node_modules\\rethinkdb\\net.js:699:22)\n    at emitOne (events.js:101:20)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1015:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  name: 'ReqlDriverError',\n  msg: 'Could not connect to localhost:28015.\\ngetaddrinfo ENOENT localhost:28015',\n  frames: undefined,\n  message: 'Could not connect to localhost:28015.\\ngetaddrinfo ENOENT localhost:28015' }\n```\n\nHowever everything works fine when the internet is back. Please help.\n"
  , issueState = "closed"
  , issueId = Id 173772486
  , issueComments = 2
  , issueMilestone =
      Just
        Milestone
          { milestoneCreator =
              SimpleUser
                { simpleUserId = Id 706854
                , simpleUserLogin = N "AtnNn"
                , simpleUserAvatarUrl =
                    "https://avatars.githubusercontent.com/u/706854?v=3"
                , simpleUserUrl = "https://api.github.com/users/AtnNn"
                , simpleUserType = OwnerUser
                }
          , milestoneDueOn = Nothing
          , milestoneOpenIssues = 0
          , milestoneNumber = 26
          , milestoneClosedIssues = 316
          , milestoneDescription =
              Just
                "These issues are neither bugs nor feature requests. Spam, user questions and accidentally created issues end up here."
          , milestoneTitle = "invalid"
          , milestoneUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/milestones/26"
          , milestoneCreatedAt = 2013 (-04) (-05) 01 : 37 : 20 UTC
          , milestoneState = "closed"
          }
  }