IssueComment
  { issueCommentUpdatedAt = 2014 (-09) (-08) 23 : 04 : 22 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 1461947
        , simpleUserLogin = N "neumino"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/1461947?v=3"
        , simpleUserUrl = "https://api.github.com/users/neumino"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/54900636"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/3020#issuecomment-54900636"
  , issueCommentCreatedAt = 2014 (-09) (-08) 23 : 04 : 22 UTC
  , issueCommentBody =
      "I honestly don't remember.\r\n\r\nI remember that I tried to reproduce this bug after the crash, but could not. I was using the JS driver and an HTTP connection.\r\nI can try to remove the validation on the interface and try that again."
  , issueCommentId = 54900636
  }