IssueComment
  { issueCommentUpdatedAt = 2013 (-10) (-07) 19 : 46 : 31 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 505365
        , simpleUserLogin = N "danielmewes"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/505365?v=3"
        , simpleUserUrl = "https://api.github.com/users/danielmewes"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/25838987"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/1380#issuecomment-25838987"
  , issueCommentCreatedAt = 2013 (-10) (-07) 19 : 46 : 31 UTC
  , issueCommentBody =
      "Tracking progress on the remaining bug in https://github.com/rethinkdb/rethinkdb/issues/728 . I'm closing this issue, because the other one is more specific and the token_pair crash which was also a part of this has been fixed."
  , issueCommentId = 25838987
  }