IssueComment
  { issueCommentUpdatedAt = 2013 (-05) (-23) 18 : 52 : 18 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 17031
        , simpleUserLogin = N "jlongster"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/17031?v=3"
        , simpleUserUrl = "https://api.github.com/users/jlongster"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/18363874"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/899#issuecomment-18363874"
  , issueCommentCreatedAt = 2013 (-05) (-23) 18 : 49 : 09 UTC
  , issueCommentBody =
      "For reference, with the Q promise library, here's my query execution function:\r\n\r\n```js\r\nfunction run(query) {\r\n    return conn.then(function(realConn) {\r\n        return Q.ninvoke(query, 'run', realConn).then(function(res) {\r\n            if(res.errors > 0) {\r\n                throw new Error(res.first_error);\r\n            }\r\n        }, function(err) {\r\n            var wrapper = new Error(err.msg);\r\n            wrapper.original = err;\r\n            throw wrapper;\r\n        });\r\n    });\r\n};\r\n```\r\n\r\nEDIT: The funny thing is that you only return the first error anyway, so why not just return that as the error parameter?"
  , issueCommentId = 18363874
  }