IssueComment
  { issueCommentUpdatedAt = 2013 (-05) (-12) 12 : 24 : 38 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 258437
        , simpleUserLogin = N "srh"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/258437?v=3"
        , simpleUserUrl = "https://api.github.com/users/srh"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/17777119"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/750#issuecomment-17777119"
  , issueCommentCreatedAt = 2013 (-05) (-12) 12 : 24 : 38 UTC
  , issueCommentBody =
      "Actually, the bug might just be in the test.  Why would we expect slm1 to get its value updated after a `slm1.get_root_view()->sync_to` call?  That would update slm2's value.\r\n\r\nStill doesn't explain the segfault..."
  , issueCommentId = 17777119
  }